---
title: "simu_functions"
author: "Anyu Zhu"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(tidyverse)
```

a function to simulate censored data.
Cox model use the Gompertz distribution as baseline
```{r}
survival_data <- function(n, beta, lambda, gamma, alpha, distribution) {
  exponential = function(u, x, lambda, beta){
    time = -log(u)/(exp(x*beta)*lambda)
  }
  
  weibull = function(u, x, lambda, gamma, beta){
    time = ( -log(u) / (exp(x * beta) * lambda) ) ^ (1 / gamma)
  }
  
  #cox?
  cox = function(u, x, lambda, alpha, beta){
    time = (1/alpha) * log(1 - (alpha * log(u) / (lambda * exp(beta * x))))
  }
  
  #treatment & times
  x = rbinom(n = n, size = 1, prob = 0.5)
  u = runif(n)
  
  if (distribution == "exponential") {
    time = exponential(u, x, lambda, beta) } 
  else if (distribution == "weibull") {
    time = weibull(u, x, lambda, gamma, beta) }
  else {
    time = cox(u, x, lambda, alpha, beta)
  }
  
  #censor
  C = rexp(n, lambda)
  
  # follow-up times
  observed_time = pmin(time, C)
  status = 1 * (time <= C)
  
  survival_data = data.frame(id = 1:n,
                             time = time,
                             observed_time = observed_time,
                             status = status,
                             x = x)
}
```

The function to fit the model
```{r}
simulate = function(sim, n, beta, dist = "exponential") {

  exp_beta = rep(NA, sim)
  weibull_beta = rep(NA, sim)
  cox_beta = rep(NA, sim)

  for (i in 1:sim) {
      data = survival_data(n, beta, distribution = dist, 
                           lambda = 0.1, gamma = 4, alpha = 4)
      # fit
      fit_exp = survreg(Surv(data$observed_time, data$status) ~ data$x, dist = "exponential") 
      fit_weibull = survreg(Surv(data$observed_time, data$status) ~ data$x, dist = "weibull")
      fit_cox = coxph(Surv(data$observed_time, data$status) ~ data$x)
      
      # Save coefficients 
      exp_beta[i] = -fit_exp$coefficients[-1]
      weibull_beta[i] = -fit_weibull$coefficients[-1] / fit_weibull$scale
      cox_beta[i] = fit_cox$coefficients[1]
      }
  
  # fit coefficients
  coef = tibble(exp = exp_beta,
                weibull = weibull_beta,
                cox = cox_beta)
  
  exp_bias = sum(exp_beta - beta)/sim
  weibull_bias = sum(weibull_beta - beta)/sim
  cox_bias = sum(cox_beta - beta)/sim
  
  performance = tibble(model = c("exp", "weibull", "cox"),
                       bias = c(exp_bias, weibull_bias, cox_bias))
  results = list(coef, performance)
  names(results) = c("coefficients", "performance")
  return(results)
}
```

Display results:

when we have different sample size:
```{r}
rst = tibble(sample_size = c(300, 350, 400, 450, 500)) %>% 
  mutate(
    output = map(.x = sample_size, 
                          ~simulate(sim = 1000, n = .x, beta = 4)$performance)) 
```

